
-- AlterTable
ALTER TABLE `visit_status_history` MODIFY `status` ENUM('KIOSK_SUBMITTED', 'WAITING_TRIAGE', 'IN_TRIAGE', 'WAITING_WINDOW', 'IN_WINDOW', 'WAITING_CLINIC', 'IN_PROGRESS', 'COMPLETED', 'NO_SHOW') NOT NULL;
