import { z } from 'zod';

export const kioskFormSchema = z.object({
    hospitalId: z.string().optional(),
    contactNo: z.string().min(10, 'Contact number should be at least 10 digits').optional(),
    firstName: z.string().min(1, 'First name is required'),
    middleName: z.string().optional(),
    lastName: z.string().min(1, 'Last name is required'),
    dobMonth: z.string().min(1, 'Month is required'),
    dobDay: z.string().min(1, 'Day is required'),
    dobYear: z.string().min(4, 'Year is required'),
    age: z.coerce.number().optional(),
    gender: z.string().min(1, 'Gender is required'),
    address: z.string().min(1, 'Address is required'),
    birthPlace: z.string().min(1, 'Birth place is required'),
    religion: z.string().optional(),
    civilStatus: z.string().min(1, 'Civil status is required'),
    hasAppointment: z.boolean().default(false),
    originStationId: z.string().optional(),
    categoryIds: z.array(z.string()).optional(),
});

export const triageFormSchema = z.object({
    isManualEntry: z.boolean().default(false),
    firstName: z.string().optional(),
    middleName: z.string().optional(),
    lastName: z.string().optional(),
    dateOfBirth: z.string().optional(),
    gender: z.string().optional(),
    address: z.string().optional(),
    birthPlace: z.string().optional(),
    religion: z.string().optional(),
    civilStatus: z.string().optional(),
    bloodPressure: z.string().optional(),
    heartRate: z.number().optional(),
    respiratoryRate: z.number().optional(),
    temperature: z.number().optional(),
    oxygenSat: z.number().optional(),
    hasFever: z.boolean().default(false),
    hasCough: z.boolean().default(false),
    hasColds: z.boolean().default(false),
    hasRashes: z.boolean().default(false),
    isInfectious: z.boolean().default(false),
    chiefComplaint: z.string().optional(),
    medicalHistory: z.string().optional(),
    triageRemarks: z.string().optional(),
    disposition: z.string().optional(),
    hasAppointment: z.boolean().default(false),
    categoryIds: z.array(z.string()).optional(),
});
