import sys
import base64
import win32print

def print_raw(printer_name, b64_data):
    try:
        # Decode the raw ESC/POS binary buffer generated by Node.js
        raw_data = base64.b64decode(b64_data)
        
        # Open Printer Spooler
        hPrinter = win32print.OpenPrinter(printer_name)
        try:
            # Start Raw Document Job
            hJob = win32print.StartDocPrinter(hPrinter, 1, ("Node ESC/POS Print Job", None, "RAW"))
            win32print.StartPagePrinter(hPrinter)
            
            # Blast the binary data straight into the printer
            win32print.WritePrinter(hPrinter, raw_data)
            
            win32print.EndPagePrinter(hPrinter)
            win32print.EndDocPrinter(hPrinter)
        finally:
            win32print.ClosePrinter(hPrinter)
            
    except Exception as e:
        print(f"win32print Error: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Missing printer name argument", file=sys.stderr)
        sys.exit(1)
        
    printer_name = sys.argv[1]
    
    # Securely read base64 data from standard input to avoid Windows terminal character limits
    b64_data = sys.stdin.read().strip()
    
    if not b64_data:
        print("Missing base64 payload from stdin", file=sys.stderr)
        sys.exit(1)
    
    print_raw(printer_name, b64_data)
